# Generated by Django 4.0.4 on 2022-04-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0002_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
